// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6gvIVnsBg9QSdP04gM3qgzEjKI5FjEEU',
    appId: '1:685223740510:android:47c849026fe4d7653ea0cf',
    messagingSenderId: '823797105784',
    projectId: 'biqoe-app',
    authDomain: 'biqoe-app.firebaseapp.com',
    storageBucket: 'biqoe-app.appspot.com',
    measurementId: 'G-SE2Y1EKLWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gvIVnsBg9QSdP04gM3qgzEjKI5FjEEU',
    appId: '1:685223740510:android:47c849026fe4d7653ea0cf',
    messagingSenderId: '685223740510',
    projectId: 'biqoe-app',
    databaseURL: 'https://biqoe-app-default-rtdb.firebaseio.com',
    storageBucket: 'biqoe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLfNGCP7GY2dwPXE5HQumjT8bP1A_OQ5o',
    appId: '1:685223740510:ios:9d79a4b0abc8347d3ea0cf',
    messagingSenderId: '685223740510',
    projectId: 'biqoe-app',
    databaseURL: 'https://biqoe-app-default-rtdb.firebaseio.com',
    storageBucket: 'biqoe-app.firebasestorage.app',
    androidClientId: '685223740510-7hdfpujjao8471o5f3524mhldljc8vv8.apps.googleusercontent.com',
    iosClientId: '685223740510-h5q40k5rngicr0l281iafuislnucrr9i.apps.googleusercontent.com',
    iosBundleId: 'com.biqoe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIY7zglX-rizV_SyBcdL3qir0WDS3nzuw',
    appId: '1:823797105784:ios:5e2d4eda4a1ec81f0ad98d',
    messagingSenderId: '823797105784',
    projectId: 'biqoe-app',
    storageBucket: 'biqoe-app.appspot.com',
    iosBundleId: 'com.biqoe.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6gvIVnsBg9QSdP04gM3qgzEjKI5FjEEU',
    appId: '1:823797105784:web:cd663272794b2cc70ad98d',
    messagingSenderId: '823797105784',
    projectId: 'biqoe-app',
    authDomain: 'biqoe-app.firebaseapp.com',
    storageBucket: 'biqoe-app.appspot.com',
    measurementId: 'G-P5D7HNWZC4',
  );
}