platform :ios, '13.0'

# CocoaPods analytics sends network stats. You can disable it by adding:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Flutter Pods
  use_frameworks!
  use_modular_headers!

  # Flutter Pod
  pod 'Flutter', :path => File.join('..', 'flutter')

  # Add any other pods you need here
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end