platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Ruta compatible con CodeMagic
  pod 'Flutter', :podspec => File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter', 'ios', 'Flutter.podspec')

  # Plugins de Flutter (generados automáticamente)
  flutter_install_ios_plugin_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
